-- MySQL Script generated by MySQL Workbench
-- 06/01/17 01:11:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LEYES
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LEYES
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS LEYES DEFAULT CHARACTER SET utf8 ;
USE LEYES ;


CREATE TABLE LEY (
  IDLEY BIGINT NOT NULL AUTO_INCREMENT,
  NUMLEY INT NOT NULL,
  FECPUBLICACION DATE NOT NULL,
  FECPROMULGACION DATE NOT NULL,
  TITULO VARCHAR(500) NULL,
  FECHAHORA DATETIME NULL,
  PRIMARY KEY (IDLEY));


CREATE TABLE USUARIO (
  IDUSUARIO BIGINT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  NOMUSU VARCHAR(20) NOT NULL,
  CLAVE VARCHAR(100) NULL,
  PREF01 INT NULL,
  PREF02 INT NULL,
  PREF03 INT NULL,
  PRIMARY KEY (IDUSUARIO));


CREATE TABLE LEYASIGNACION (
  IDLEYASIGNACION BIGINT NOT NULL AUTO_INCREMENT,
  IDLEY BIGINT NOT NULL,
  IDUSUARIO BIGINT NOT NULL,
  REVISADA INT NOT NULL,
  DESCRIPCION VARCHAR(300) NOT NULL,
  PRIMARY KEY (IDLEYASIGNACION));


/*Creación de registros 1234/123478*/
INSERT INTO USUARIO(NOMUSU,CLAVE,NOMBRE)
     VALUES ('flopez','81dc9bdb52d04dc20036dbd8313ed055','Fabián Lopez');

INSERT INTO USUARIO(NOMUSU,CLAVE,NOMBRE)
     VALUES ('psuazo','fcea920f7412b5da7be0cf42b8c93759','Patricio Suazo');
	 
	 
/* Agregar registros*/
INSERT INTO LEY(NUMLEY,FECPUBLICACION,FECPROMULGACION,FECHAHORA,TITULO) VALUES
(21014,'2017-5-26','2017-5-18',NOW(),'Exige incorporar a los contratos de compraventa de inmuebles su superficie total y útil, y de terrazas bodegas y estacionamientos'),
(21011,'2017-5-4','2017-5-2',NOW(),'Modifica la fecha de la cuenta que debe rendir el presidente de la república ante el congreso pleno'),
(21009,'2017-4-28','2017-4-21',NOW(),'Facilita pago de propinas en establecimientos de atención al público'),
(21010,'2017-4-28','2017-4-18',NOW(),'Extiende y modifica la cotización extraordinaria para el seguro social contra riesgos de accidentes del trabajo y enfermedades profesionales, y crea el fondo que financiará el seguro para el acompañamiento de los niños y niñas'),
(21003,'2017-4-21','2017-4-10',NOW(),'Extiende los beneficios de la ley nº 20.948 a los funcionarios y funcionarias de la junta nacional de jardines infantiles, establece normas específicas para el incentivo de la ley nº 20.213 y modifica los requisitos de ingreso y promoción de la función de supervisión de la planta de profesionales de dicho servicio'),
(21007,'2017-4-6','2017-3-30',NOW(),'Establece el 6 de abril de cada año como día nacional del deporte para el desarrollo y la paz'),
(21002,'2017-3-31','2017-3-29',NOW(),'Crea una asignación de fortalecimiento de redes asistenciales para el personal que indica'),
(21006,'2017-4-4','2017-3-29',NOW(),'Modifica diversos cuerpos legales que rigen al sector educativo, en materia de subvención escolar preferencial, situación de becarios de postgrado, desarrollo profesional docente y otras'),
(21008,'2017-4-5','2017-3-29',NOW(),'Establece el día 14 de abril como día nacional del locutor'),
(21005,'2017-4-7','2017-3-29',NOW(),'Moderniza el consejo nacional de televisión, concede las asignaciones que indica y delega facultades para fijar su planta de personal'),
(21004,'2017-3-29','2017-3-23',NOW(),'Modifica el código procesal penal, para evitar la dilación injustificada del proceso penal'),
(21001,'2017-3-22','2017-3-9',NOW(),'Establece el nuevo escalafón del servicio de personal del ejército'),
(20997,'2017-3-13','2017-3-1',NOW(),'Moderniza la legislación aduanera'),
(20988,'2017-2-11','2017-2-3',NOW(),'Regula la donación cruzada de órganos entre vivos'),
(20996,'2017-2-10','2017-2-3',NOW(),'Otorga bonificación adicional por retiro al personal no académico ni profesional de las universidades del estado y faculta a estas para conceder otros beneficios transitorios'),
(20999,'2017-2-9','2017-1-31',NOW(),'Modifica la ley de servicios de gas y otras disposiciones que indica'),
(20995,'2017-1-31','2017-1-25',NOW(),'Concede la nacionalidad chilena, por especial gracia, a la ciudadana estadounidense señora Valene Leah Georges Larsen'),
(20992,'2017-2-2','2017-1-25',NOW(),'Regula feriado por censo'),
(20993,'2017-1-28','2017-1-23',NOW(),'Modifica diversos cuerpos legales para facilitar el funcionamiento del sistema escolar'),
(20994,'2017-1-27','2017-1-23',NOW(),'Regula beneficio que indica, para trabajadores de establecimientos de educación parvularia administrados en convenio con la junta nacional de jardines infantiles');

